# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Build
on: [push, create, release]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Lint
      run: npm run lint --if-present
    - name: Build
      run: npm run build --if-present
  deploytesting:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Lint
      run: npm run lint --if-present
    - name: Build
      run: npm run build --if-present
    - name: Publish to testing guild
      run: npm run publish --if-present
      env:
        DEPLOYMENTS: ${{secrets.PYLON_API_DEPLOYMENTS_TEST_DEPLOY}}
        API_TOKEN: ${{secrets.PYLON_API_KEY}}